//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCharityTHeme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PayPalPayment
    {
        public int PaymentID { get; set; }
        public Nullable<int> DonationId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CardNumb { get; set; }
        public string ExpiryMonth { get; set; }
        public string ExpiryYear { get; set; }
        public string CVCODE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Tbl_Donation Tbl_Donation { get; set; }
    }
}
